twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['form_themes/tailwind_3.html.twig']

    paths:
        # Le dossier où mes images se trouvent.
        '%kernel.project_dir%/public/email_images': img

when@test:
    twig:
        strict_variables: true
