<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '11d48b9d4a0e99f53f35ab77b03015ee',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default',
  'DATABASE_URL' => 'mysql://u439277287_papoel:wb2jppDomo@127.0.0.1:3306/u439277287_ape_pasteur',
  'RECAPTCHA3_KEY' => '6LdpYLEjAAAAAF0MVyFzl78ZfjWrfHVjt8OluqXX',
  'RECAPTCHA3_SECRET' => '6LdpYLEjAAAAAG_t0LYboaGbj12ANM5DbhNesz9T',
  'STRIPE_KEY_PUBLIC' => 'pk_live_51MU6H5FLFSbTqJ0wvJhHSHOHRFk8QfcUyxKvoUzj1bWIvHXU9WxJGfgyfkq9CSKOSCqbDMdX2JLf66XG5fQ5aJ7x00zTspy2UK',
  'STRIPE_KEY_SECRET' => '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',
  'STRIPE_WEBHOOK_SECRET' => 'whsec_8tyW5xq9AIgOeTJh75TvP9XgqUTCxWLT',
  'MAILER_DSN' => 'smtp://contact@aperp.info:59@aperP@smtp.hostinger.com:465',
);
