# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.contact_email: contact@aperp.info
    app.name: Association des Parents d'Élèves - Rousies Pasteur
    upload_dir: '/uploads/images/events'
    STRIPE_KEY_SECRET: '%env(resolve:STRIPE_KEY_SECRET)%'
    STRIPE_KEY_PUBLIC: '%env(resolve:STRIPE_KEY_PUBLIC)%'
    STRIPE_WEBHOOK_SECRET: '%env(resolve:STRIPE_WEBHOOK_SECRET)%'
    STRIPE_WEBHOOK_SECRET_ORDER: '%env(resolve:STRIPE_WEBHOOK_SECRET_ORDER)%'
    maintenance_file: '%kernel.project_dir%/public/.maintenance'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $uploadDir: '%upload_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\EventListener\MaintenanceListener:
        arguments:
            - '%maintenance_file%'
            - '@twig'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
